image:
  repository: <ECR_URL_PLACEHOLDER>
  tag: "latest"
  pullPolicy: IfNotPresent

service:
  type: LoadBalancer
  port: 80
  targetPort: 8000

resources: {}

autoscaling:
  enabled: true
  minReplicas: 2
  maxReplicas: 6
  targetCPUUtilizationPercentage: 70

env:
  DJANGO_SETTINGS_MODULE: "config.settings"
  DEBUG: "False"
  ALLOWED_HOSTS: "*"
  CORS_ALLOWED_ORIGINS: "*"
  RATE_LIMITING: "100/hour"
  DJANGO_SECRET_KEY: "test-key"
  DJANGO_ALLOWED_HOSTS: "*"

# Бонус (Ingress) — выключено по умолчанию
ingress:
  enabled: false
  className: nginx
  host: yourdomain.com
  path: /
  pathType: Prefix
  tls: false
  annotations: {}
  # пример:
  # annotations:
  #   cert-manager.io/cluster-issuer: letsencrypt-prod
